[package]
name = "panic_test"
version = "0.1.0"
authors = ["pi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#eyre = "0.4"
#color-eyre = "0.3"
backtrace = "0.3"
